### ISSUE TITLE
Warp mode

### ISSUE THREAD

**Issue by hvlife-dev** [rhysnewell/fftconvolve#5]
Hey
Is there any way to "warp" convolution? I mean, when kernel is reaching outside, missing values are taken from the opposite edge or corner.
I've tried to manually extend ndarray ( add last rows behind first... ), but without any success.
If you are wondering I just need to "tunnel entities through walls" in discrete version of Game of Life.
Thanks in advance

**Comment by hvlife-dev** [comment]
I've done that myself by padding 2d input vector using ndarray-ndimage crate ( padding width is determined by kernel radius ), and after convolving extracting "center" with the help of slice(). In my program fps dropped by negligible amount, so I'm happy with the result.

**Comment by rhysnewell** [comment]
Sorry, I didn't get time to work on a solution for this. I'll keep it in mind in future when I get some time to work on this
